POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso Angular"
}

###
GET http://localhost:3333/courses?orderBy=title&page=2

###
GET http://localhost:3333/courses/b020573c-611e-4820-89b1-9abac3e054d1